---
title: "Start Here"
---

### Hello my love! 

I wanted to make some special for you for our anniversary, but ran into the problem of not being able to make anything physical that would capture all of my feelings for you because we are studying abroad and can't really take a lot of stuff with us and printing costs for all of these images would be rather high. So I found a solution: a website! I always like showing you the data I've collected on our relationship, and I think it would be fun to have a bunch of it all in one place, so I've created a few visualizations for everything. So here's a description of each of the tabs, so you can decide what you want to look at. 

### Calendars: 
I figured out how to make calendars and I wanted to highlight a lot of the special dates in our relationship, like the dates when we went on dates or the ones when I visited you during study abroad. 

### Dates: 
Here I've written a little description for each of the dates we've been on based on what I remember from it and why it was important to me.

### Graphs:
Here are all the graphs that I made! These are random things like how many dates we went on per month, which locations they were in, and the date score graph.

### Maps:
Here are maps of each region of the world that we've gone on dates in. These are interactable and you can zoom in and out and hover over the little date icons. 

I hope you like this :) I love you so so much 

