---
title: "Maps"
---

Where we were! 

## Connecticut
```{r, echo=FALSE, message=FALSE, warning=FALSE}
#packages
library(leaflet)
library(tidyverse)
library(qacBase)
library(googlesheets4)
library(fontawesome)

#data importation

#Read google sheets data into R
df <- read_sheet('https://docs.google.com/spreadsheets/d/11wtPXCMVumSOinF0H4kGcZs8EW5dwq5bK1DVcZDqeKk/edit?usp=sharing')

############## MAPS #############

#NYC dataset
df.nyc <- df[which (df$location=="NYC"), ]

#CT dataset
df.ct <- df[which(df$location=="CT"),]

#Paris dataset
df.p <- df[which(df$location=="Paris"),]

#Oxford dataset
df.ox <- df[which(df$location=="Oxford"|df$location=="London"),]

#Rome dataset
df.rm <- df[which(df$location=="Rome"|df$location=="Ercolano"),]

#code for map with regular markers 
icons <- awesomeIcons(
  icon = 'heart',
  iconColor = 'white',
  library = 'ion',
  markerColor = c("red", "orange", "green", 
                  "lightblue", "blue", "darkpurple")
)

#connecticut-centered
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Voyager) %>% 
  setView(lng = -72.65036230409424, lat = 41.55732837751208 ,zoom = 15) %>% 
  addAwesomeMarkers(lng = df.ct$lon, lat = df.ct$lat, icon=icons, 
                    label=as.character(df.ct$activity))
```

## NYC 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
#NYC-centered
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Voyager) %>% 
  setView(lng = -73.88707151896678, lat = 40.704741216555426 ,zoom = 11) %>% 
  addAwesomeMarkers(lng = df.nyc$lon, lat = df.nyc$lat, icon=icons, 
                    label=as.character(df.nyc$activity))
```

## Paris
```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Paris-centered
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Voyager) %>% 
  setView(lng = 2.3172509060537636, lat = 48.851931201333045, zoom = 11) %>% 
  addAwesomeMarkers(lng = df.p$lon, lat = df.p$lat, icon=icons, 
                    label=as.character(df.p$activity))
```

## Oxford/London

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Oxford-centered
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Voyager) %>% 
  setView(lng = -0.7562696721612163, lat = 51.63158387815886,zoom = 9) %>% 
  addAwesomeMarkers(lng = df.ox$lon, lat = df.ox$lat, icon=icons, 
                    label=as.character(df.ox$activity))
```

## Italy 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Italy-centered
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Voyager) %>% 
  setView(lng = 13.708644868499244, lat = 41.37637681386648,zoom = 8) %>% 
  addAwesomeMarkers(lng = df.rm$lon, lat = df.rm$lat, icon=icons, 
                    label=as.character(df.rm$activity))

